language: php

php:
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
  - php: nightly

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

before_intall:
  - phpenv config-rm xdebug.ini
  - pecl install pcov
  - echo "extension=pcov.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer self-update --snapshot
  - composer update $COMPOSER_OPTS

script:
  - composer test

jobs:
  include:
    - stage: coverage
      script:
        - vendor/bin/phpunit --coverage-clover=coverage.xml
        - bash <(curl -s https://codecov.io/bash)

git:
  depth: 5

group: travis_latest
